baseURL = "https://digitaljoni.com/"
languageCode = "en-US"
title = "digitaljoni"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-7914706-1"

theme = "digitaljoni"

[blackfriday] 
  hrefTargetBlank = true

[permalinks]
  post = "/:year/:slug"
      
[params]
  logo = "logo-2018.png"
  pageLogo = "logo2.png"
  homebackground = "digitaljoni-header.jpg"
  author = "Joennie Sindo"
  description = "Web/Mobile Application Development"

[params.social]
  github="digitaljoni"
  instagram="digitaljoni"
  twitter="digitaljoni"
  facebook="digitaljoni"
  google="+digitaljoni"
  linkedin="digitaljoni"
  email="joni@digitaljoni.com"

## Main Menu
[[menu.main]]
  name = "home"
  weight = 100
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "projects"
  identifier = "projects"
  weight = 200
  url = "/projects/"
[[menu.main]]
  name = "resources"
  identifier = "resources"
  weight = 200
  url = "/resources/"