baseURL = "https://digitaljoni.com/"
googleAnalytics = "UA-7914706-1"
languageCode = "en-US"
theme = "digitaljoni"
title = "digitaljoni"
[blackfriday]
hrefTargetBlank = true
[[menu.main]]
name = "blog"
url = "/blog/"
weight = 2
[[menu.main]]
identifier = "resources"
name = "resources"
url = "/resources/"
weight = 4
[[menu.main]]
identifier = "projects"
name = "projects"
url = "/projects/"
weight = 3
[[menu.main]]
identifier = "home"
name = "home"
url = "/"
weight = 1
[params]
author = "Joennie Sindo"
description = "Web/Mobile Application Development"
homebackground = "digitaljoni-header.jpg"
logo = "logo-2018.png"
pageLogo = "logo2.png"
[params.social]
email = "joni@digitaljoni.com"
facebook = "digitaljoni"
github = "digitaljoni"
google = "+digitaljoni"
instagram = "digitaljoni"
linkedin = "digitaljoni"
twitter = "digitaljoni"
[permalinks]
post = "/:year/:slug"
